const treatment = [
    //tomato
    {
        disease: "Tomato_Target_Spot",
        detection: "Look for the disease on the bottom leaves. Look for tiny brown spots with yellow margins. Look for larger spots up to 10 mm that have ring patterns. Spots may be present on the stems and on the fruit.",
        impact: "The fungus causes plants to lose their leaves; it is a major disease. If infection occurs before the fruit has developed, yields are low. This is a common disease on tomato in Pacific island countries. The disease occurs in the screen house and in the field.",
        cure: "Warm wet conditions favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest. It is important to spray both sides of the leaves."
    },
    {
        disease: "Tomato_Bacterial_spot",
        impact: "Bacterial spot is a serious disease. It is especially severe in warm, wet and windy conditions, causing plants to lose their leaves. Damage to fruit occurs (i) when the disease comes early as mostly young fruit are infected; and (ii) when leaves drop exposing the fruit to the sun.",
        detection: "Look for many small (2-3 mm) irregular spots on the leaves, leaf stalks, stems and fruits. Spots on the leaf stalks and stems are elongate, i.e., longer than they are wide. Look for scabby spots on the fruits with transparent margins.",
        cure: "Use copper fungicides, or copper plus mancozeb. It is very important to have healthy seedlings free from bacterial spot, so spraying should start in the nursery, and continue at 7-10 day intervals in the field. Spraying early, when the plants are young, is especially important as in wet, windy weather, sprays alone often fail to give adequate control."
    },
    {
        disease: "Tomato_Early_blight",
        impact: "Early blight of tomato is a serious disease requiring control measures, including fungicide applications. The disease occurs wherever tomato (and potato, Photos 6-8) is grown, and can cause severe defoliation, resulting in fewer, smaller fruit. Loss of yield is difficult to estimate, but probably at least 5%. Many millions of dollars are spent on fungicides to control the disease.",
        detection: "Look for the circular to angular brown spots on the leaves, checking to see if they have the characteristic target-like rings. Look to see more elongated spots on the stems. Look for fruits which produce dense black spore masses of the fungus.",
        cure: "Use protectant fungicides, mancozeb, chlorothalonil or copper products. Systemic products are available, e.g., strobilurins, although they are expensive and, if used too often, the fungus may develop resistance to them."
    },
    {
        disease: "Tomato_Late_blight",
        impact: "Late blight is one of the world's worst plant diseases, despite efforts to control it for 150 years. It causes large losses in yields of tomatoes (and potatoes), and requires the application of expensive fungicides to maintain control. Since the 1990s, a second strain (A2) has appeared in Europe, presumably and introduction from Mexico. Previously only one strain (A1) was known in Europe. There is now the potential for new strains of the oomycete through sexual reproduction, and these may be more aggressive, and/or tolerant to fungicides than those present previously. The A2 strain has spread to many countries, with the result that there are new strains that are more aggressive, produce more spores and have increased tolerance to fungicides.",
        detection: "Look for spots and patches on the leaves which grow rapidly and produce a furry white growth on the underside. Look for the white growth after putting the leaves in a plastic bag overnight. Check tomato plants regularly for infections, especially when the days are cool and wet, or overcast with heavy dews or mists.",
        cure: "Ideally, use a preventative spray before symptoms are seen, e.g., a copper product, chlorothalonil, or mancozeb. If using a systemic product, e.g., metalaxyl, cymoxanil, or dimethomorth, or a strobilurin, alternate single sprays with two sprays of a preventative product. Also, note that in some countries mancozeb is not used on fruit if growers harvest two or more times a week as the preharvest interval is 5 days (i.e., the time between the last spray and harvest). In addition, phosphorous acid has a direct and indirect effect on oomycetes, and should be tested. The indirect effect comes from its ability to stimulate plants' natural defense response against attacks by pathogens."
    },
    {
        disease: "Tomato_Leaf_Mold",
        impact: "The fungus causes a serious disease in cooler, wetter areas. The loss of leaves, from the bottom of the plant upwards, is rapid. Yield reduction is related to the time of infection. If plants are infected before fruits are formed, considerable crop loss occurs. In severe cases, the flowers and, occasionally, the fruit are attacked. Infected flowers may fail to set fruit. Occasionally, the fungus causes an internal blackening of the fruit. Note, in Samoa, fruit yields of susceptible varieties were tripled when fungicides were used to control the disease. In Solomon Islands, it is an important disease in the highlands. It is less common in coastal areas where another leaf mould disease occurs on tomatoes called black leaf mould, Pseudocercospora fuligena",
        detection: "Look for the yellow spots and rapidly developing irregular patches on the upper surfaces of the lower leaves, with brown to green areas on the under surface. Look for plants where leaves dry up and die rapidly. Note, there is another disease that has similar symptoms. It is called tomato black leaf mould, caused by the fungus, Pseudocercospora fuligena. This fungus and Passalora fulva can only be distinguished by looking at their spores under a microscope.",
        cure: "The cool, wet, conditions in Pacific island countries favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the yellow spots are first seen, and continue at 10-14-day intervals until 3-4 weeks before last harvest. It is important to spray both sides of the leaves."
    },
    {
        disease: "Tomato_Spider_mites_Two_spotted_spider_mite",
        impact: "The extent of the damage caused by mites often depends on rainfall. When rainfall is low, mite populations are high and reduce crop yields. On taro, for instance, yellowing and early maturity of plants occurs and corm size is reduced. Damage is particularly severe during droughts and, presumably, outbreaks will increase with climate change.",
        detection: "Look at the underside of leaves, particularly near the veins for the presence of mites, using a hand lens and/or a microscope. Look for webbing, which can be seen when mites are present in large numbers. The white spots on the upper leaf surface and the presence of webs below are signs of their presence. Look for spots on the mites; the spots are reddish-brown to yellowish-green, depending on the species.A good way to detect if mites are present is to place a sheet of white paper beneath the leaves and strike the leaves sharply. The mites fall onto the paper and can be more easily seen than on the green leaves.",
        cure: "If pesticides are used, they should be applied carefully. Rotate between different chemical groups, to prevent resistance developing to any one of them. There are several products registered in Australia for use against red spider mites (abamectin, bifenthrin, chlorpyriphos, dimethoate, malathion), but note that they are toxic to natural enemies and that tomato red spider mite may tolerate them. Not all insecticides kill mites, and those that do may not kill all the stages. Eggs are particularly resistant to pesticides and so, too, are larvae and nymphs, especially when moulting, as they do not feed. More than one application is needed at 5-10 days apart. Use products containing sulphur - a product allowed under organic certification. Use abamectin, a product derived from a soil bacterium. It is absorbed into plants but is not systemic."
    },
    {
        disease: "Tomato_Tomato_mosaic_virus",
        impact: "The mosaic virus is a parasite that destroys plants, gardens, and crops down to their molecular level. Once a plant contracts the mosaic virus, the infected plant can then spread the virus to other plants and even affect an entire harvest if left untreated. Mosaic viruses affect a wide variety of horticultural and vegetable crops — roses, beans, tobacco, tomatoes, potatoes, cucumbers, pumpkins, squash, melons, and peppers.",
        detection: "The leaves are mottled with yellow, white, and light and dark green spots, which appear to be elevated. This gives the leaves a blister-like appearance. Plants are often stunted, or they grow poorly. Plants may have other deformities and their leaves may be crinkled or wavy. ",
        cure: "There are no cures for viral diseases, such as the mosaic virus, once a plant is infected. Fungicides will NOT treat this viral disease. Plant resistant varieties when available or purchase transplants from a reputable source. Do NOT save seeds from infected crops. Spot treat with least-toxic, natural pest control products, such as Safer Soap, Bon-Neem, and diatomaceous earth, to reduce the number of disease-carrying insects"
    },
    {
        disease: "Tomato_Tomato_YellowLeaf_Curl_Virus",
        impact: "Tomato yellow leaf curl virus is undoubtedly one of the most damaging pathogens of tomato, and it limits production of tomato in many tropical and subtropical areas of the world.  Fruit production is dramatically reduced, particularly when plants are infected at an early age, and it is not uncommon for losses of 100% to be experienced in fields with heavily infected plants.",
        detection: "Infected tomato plants initially show stunted and erect or upright plant growth; plants infected at an early stage of growth will show severe stunting. However, the most diagnostic symptoms are those in leaves. Leaves of infected plants are small and curl upward; and show strong crumpling and interveinal and marginal yellowing. The internodes of infected plants become shortened and, together with the stunted growth, plants often take on a bushy appearance, which is sometimes referred to as 'bonsai' or broccoli'-like growth. Flowers formed on infected plants commonly do not develop and fall off (abscise).",
        cure: "Once infected with the virus, there are no treatments against the infection. Control the whitefly population to avoid the infection with the virus. Insecticides of the family of the pyrethroids used as soil drenches or spray during the seedling stage can reduce the population of whiteflies. However, their extensive use might promote resistance development in whitefly populations."
    },
    {
        disease: "Tomato_Septoria_leaf_spot",
        impact: "Septoria leaf spot is a very common disease of tomatoes. It is caused by a fungus (Septoria lycopersici) and can affect tomatoes and other plants in the Solanaceae family, especially potatoes and eggplant, just about anywhere in the world. Although Septoria leaf spot is not necessarily fatal for your tomato plants, it spreads rapidly and can quickly defoliate and weaken the plants, rendering them unable to bear fruit to maturity.",
        detection: " Symptoms spread upwards from oldest to youngest growth. Small, water-soaked grey circular spots with dark-brown margins appear on the undersides of older leaves. At later stages of the disease, the spots enlarge and coalesce, and black dots appear in their centers. The same pattern may also be observed on stems and blossoms, but rarely on fruit. Heavily infected leaves will turn slightly yellow, wither, and fall off. The defoliation leads to sun scalding of fruit. ",
        cure: " Always consider an integrated approach with preventive measures together with biological treatments if available. Fungicides containing maneb, mancozeb, chlorothalonil effectively control Septoria leaf spot. Apply at 7 to 10 day intervals throughout the season, mainly during flowering and fruit setting. Follow harvest restrictions listed on the pesticide label. "
    },
    //potato
    {
        disease: "Late Blight",
        impact: "Late blight is one of the world's worst plant diseases, despite efforts to control it for more than 150 years. It causes large losses in yields of potatoes and tomatoes, and requires the application of expensive fungicides to maintain control. Until the 1980s, the A2 strain was known only in Mexico. Since then it has spread to many countries, and where mating with the A1 strain occurs the offspring are more aggressive, produce more spores and have increased tolerance to fungicides.",
        detection: "Look for spots and patches on the leaves which grow rapidly and produce a furry white growth on the underside. Look for the white growth after putting the leaves in a plastic bag overnight. Check the plants regularly for infections, especially when the days are cool and wet, or overcast with heavy dews, fogs or mists.",
        cure: "Use a preventative spray of a contact fungicide before symptoms are seen, e.g., a copper product, chlorothalonil, mancozeb or polyram. If using a systemic product that may control the disease after infection, e.g., metalaxyl, cymoxanil, dimethomorph, or a strobilurin, alternate single sprays with two sprays of a preventative product to avoid the development of resistant strains of late blight. Manufacturers of cymoxanil and dimethomorph recommend the addition of either mancozeb or polyram to these products. It is very important to follow manufacturers recommendations if using systemic products. Copper fungicides - copper hydroxide and copper sulfate - can be used on organic crops, although because of copper toxicity, alternatives, such as phosphorous acid and horticultural oils may be necessary. The frequency of spray application will depend on the susceptibility of the potato variety and whether environmental conditions favour late blight disease. "
    },
    {
        disease: "Early Blight",
        impact: "Historically, was not considered to be of economic importance in the UK. However in recent years it has become more conspicuous on the continent, Scandinavia and the UK, particularly in the warmer summers of 2010 and 2011. The reduced use of mancozeb in blight control programmes and the introduction of more susceptible varieties are also thought to have contributed to the increased incidence of this pathogen. The disease can cause yield losses if uncontrolled.",
        detection: "Early blight in potato tends to occur in more advanced crop cycles. The symptoms appear as small spots on the leaves in the form of concentric rings that darken as they grow. The infection tends to start on the leaves nearest to the soil, which are the oldest.",
        cure: "Since most commercially acceptable potato cultivars are susceptible to early blight, the application of foliar fungicides is the primary management tactic. Mancozeb and chlorothalonil are perhaps the most frequently used protectant fungicides for early blight management but provide insufficient control under high disease pressure. Therefore, the application of locally systemic and translaminar fungicides often is necessary for control at high levels of disease pressure, especially under irrigation. Fungicide selection and rotation should be approached with thought to obtain effective disease control and prevent the early blight pathogen from further fungicide resistance development. Rotate fungicides with different modes of action. Fungicides with the same mode of action should not be applied in consecutive applications."
    },
    //cotton
    {
        disease: "Bacterial blight",
        impact: "Bacterial blight in cotton, also known as seedling blight, angular leaf spot, and boll rot, is caused by Xanthomonas citri pv. malvacearum (formerly referred to as Xanthomonas campestris pv. malvacearum and Xanthomonas malvacearum). In the 1940s and 1950s, bacterial blight caused severe damage throughout cotton-growing areas until the release of resistant cotton cultivars starting in 1955. The severity of this disease is greatly influenced by environmental conditions as the disease thrives in extremely warm, humid environments, which some regions are experiencing this growing season.",
        detection: "Bacterial blight infections can affect any above-ground portions of the plant and at any point of plant development. Lesions associated with Xanthamonas begin as an angular leaf spot with a red to brown border. Tissues surrounding lesions may also become yellow, giving the appearance of a 'halo' surrounding the lesion. The angular appearance of lesions is due to restriction of the lesion by fine veins of the cotton leaf, and bacteria may spread along the leaf veins causing blackened lesions along major veins. Leaf petioles and stems may also become infected (cotton black leg), which can lead to premature defoliation of the plant. Black cankers on stems or branches may girdle the plant causing the portions to die above the canker. Additionally, a white waxy crust containing the bacterium may also form on old leaf spots or cankers.",
        cure: "Delint the cotton seeds with concentrated sulphuric acid at 100ml/kg of seed. Treat the delinted seeds with carboxin or oxycarboxin at 2 g/kg or soak the seeds in 1000 ppm Streptomycin sulphate overnight. Remove and destory the infected plant debris. Rogue out the volunteer cotton plants and weed hosts. Follow crop rotation with non-host crops. Early thinning and early earthing up with potash. Grow resistant varieties like Sujatha, 1412 and CRH 71. Spray with Streptomycin sulphate +Ttetracycline mixture 100g along with Copper oxychloride at 1.25 Kg/ha."
    },
    {
        disease: "Curl virus",
        impact: " Cotton leaf curl virus attack had an adverse effect on the plant height of all the susceptible lines/cultivars of cotton. A decrease of 31.8 % in the height (Av. of all lines/cultivars) of diseased plants was recorded compared with those of healthy plants.",
        detection: " The primary symptom of cotton leaf curl virus is the upward curling of leaves. Additionally, leaf veins can thicken and darken, and outgrowths (enactions) may form on the undersides of leaves, typically in the shape of leaves. Flowers may stay closed and then drop along with the bolls. If plants are infected early in the season, their growth will be stunted and yield will be reduced significantly. ",
        cure: "Always consider an integrated approach with preventive measures together with biological treatments if available. There are no known methods for preventing or reducing cotton leaf curl virus. Chemical control in the form of insecticides can be used to control the whitefly population, such as imadacloprid or dinotefuran. Insecticides should be approached with caution however, because excessive usage of insecticides has caused many whitefly species to become resistant to them. To reduce the likelihood of this occurring, be sure to rotate between insecticides."
    },
    {
        disease: "Fussarium wilt",
        impact: "Several fungal diseases are problematic for cotton growers, including Verticillium wilt (Verticillium dahliae), damping-off (Rhizoctonia spp. and Pythium spp.), Ascochyta blight (Ascochyta gossypii), black root rot (Thielaviopsis basicola) and various leaf spots. Fusarium wilt is of particular concern to growers as the pathogen frequently causes severe economic losses and persists in fields for many years.",
        detection: "The disease affects the crop at all stages. The earliest symptoms appear on the seedlings in the cotyledons which turn yellow and then brown. The base of petiole shows brown ring, followed by wilting and drying of the seedlings. In young and grown up plants, the first symptom is yellowing of edges of leaves and area around the veins i.e. discoloration starts from the margin and spreads towards the midrib. The leaves loose their turgidity, gradually turn brown, droop and finally drop off.",
        cure: "Treat the acid delinted seeds with Carboxin or Carbendazim at 2 g/kg. Remove and burn the infected plant debris in the soil after deep summer ploughing during June-July. Apply increased doses of potash with a balanced dose of nitrogenous and phosphatic fertilizers. Apply heavy doses of farm yard manure or other organic manures. Follow mixed cropping with non-host plants. Grow disease resistant varieties of G. hirsutum and G. barbadense like Varalakshmi, Vijay Pratap, Jayadhar and Verum. Spot drench with Carbendazim 1g/litre."
    },
    //corn
    {
        disease: "Corn_Blight",
        impact: "Northern corn leaf blight (NCLB), caused by the fungus Exserohilum turcicum, is an increasingly important disease in the U.S. Corn Belt. The disease has appeared annually in Indiana, and has increased in prevalence since the mid- to late 2000s. NCLB can cause yield loss if it develops before or during the tasseling and silking phases of corn development. ",
        detection: 'Symptoms usually appear first on the lower leaves. Leaf lesions are long (1 to 6 inches) and elliptical, gray-green at first but then turn pale gray or tan. Under moist conditions, dark gray spores are produced, usually on the lower leaf surface, which give lesions a "dirty" gray appearance. Entire leaves on severely blighted plants can die, so individual lesions are not visible. Lesions may occur on the outer husk of ears, but the kernels are not infected.',
        cure: "Fungicide sprays like Custodia, Fortix and Stratego YLD are recommended for fresh market sweet corn, hybrid seed production, and dent corn fields planted with susceptible hybrids. The spray schedule should start when the first lesions appear on the leaf below the ear on 50% of the plants. Applications made at tasseling or silking (VT/R1) provide the most consistent results in terms of disease control and yield response."
    },
    {
        disease: "Corn_Common_Rust",
        impact: "Common rust rarely reaches levels that cause yield loss in commercial hybrids. It is most problematic during prolonged periods of cool, wet weather. Rust diseases are generally easy to identify by the appearance of brown pustules.",
        detection: 'Rust pustules usually first appear in late June. Early symptoms of common rust are chlorotic flecks on the leaf surface. These soon develop into powdery, brick-red pustules as the spores break through the leaf surface. Pustules are oval or elongated, about 1/8 inch long, and scattered sparsely or clustered together. The leaf tissue around the pustules may become yellow or die, leaving lesions of dead tissue. The lesions sometimes form a band across the leaf and entire leaves will die if severely infected. ',
        cure: "Fungicides have been used against both common and southern rust, but they are usually not needed in maize because of the resistance bred into commercial varieties. However, foliar fungicides may have a use on sweet corn. A number of protectant fungicide have been recommended: e.g., chlorothalonil and mancozeb. Plants are monitored and sprays commence when there are on average six pustules per leaf."
    },
    {
        disease: "Corn_Gray_Leaf_Spot",
        impact: "Gray leaf spot, caused by the fungus Cercospora zeae-maydis, occurs virtually every growing season. If conditions favor disease development, economic losses can occur. Gray leaf spot is typically the most serious foliar disease of corn. Gray leaf spot requires extended periods of high humidity and warm conditions. It can be confused with other foliar diseases of corn.",
        detection: 'The disease first appears in the form of small, necrotic spots with halos. These usually expand to become rectangular lesions, about 1/8 inch wide by up to 2 inches to 3 inches long and gray to brown in appearance. Mature lesions usually have distinct parallel edges and appear opaque when put up to the light, but the lesions hybrids vary widely in shape and color.',
        cure: "Fungicides containing pyraclostrobin and metconazole are available for in-season gray leaf spot management. It is important to remember that a fungi-cide application is an additional cost to corn production, so growers must consider economic factors (corn market price and fungicide application cost) and other disease factors before deciding whether to apply a fungicide to manage gray leaf spot."
    },
]

function getCure(disease) {
    for (let index = 0; index < treatment.length; index++) {
        if (treatment[index].disease == disease) {
            return treatment[index]
        }

    }
}

module.exports = { getCure };